import { GoogleGenAI, Modality } from "@google/genai";

export const editImage = async (
  base64ImageData: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const candidate = response.candidates?.[0];
    const parts = candidate?.content?.parts;

    if (parts) {
      for (const part of parts) {
        if (part.inlineData) {
          const base64ImageBytes: string = part.inlineData.data;
          // The API returns raw base64, we add the data URI prefix for browser rendering
          return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
        }
      }
    }
    
    let reason = "No image content was generated by the API.";
    if (candidate?.finishReason && candidate.finishReason !== 'STOP') {
      reason = `Generation failed: ${candidate.finishReason}.`;
    } else if (response.promptFeedback?.blockReason) {
      reason = `Request blocked: ${response.promptFeedback.blockReason}.`;
    }
    
    throw new Error(reason);

  } catch (e) {
    console.error("Gemini API call failed:", e);
    const errorMessage = e instanceof Error ? e.message : "An unknown error occurred during image generation.";
    throw new Error(`Failed to generate image: ${errorMessage}`);
  }
};
